# Generated by Django 3.1.14 on 2025-01-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemons',
            new_name='Pokemon',
        ),
    ]
